version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: policy-etl-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: policy_etl_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init-scripts:/docker-entrypoint-initdb.d
    networks:
      - policy-etl-network

  # Opsiyonel: PostgreSQL Admin UI (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: policy-etl-pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@policy-etl.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "8080:80"
    depends_on:
      - postgres
    networks:
      - policy-etl-network

volumes:
  postgres_data:
    driver: local

networks:
  policy-etl-network:
    driver: bridge
