spring:
  application:
    name: policy-etl

  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/policy_etl_db
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      connection-timeout: 20000
      idle-timeout: 300000
      max-lifetime: 1800000

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true

  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        jdbc.time_zone: UTC
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.batch_size: 25
        order_inserts: true
        order_updates: true
        jdbc.batch_versioned_data: true
    show-sql: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: always

logging:
  level:
    root: INFO
    org.springframework.batch: INFO
    org.hibernate.SQL: WARN
    org.hibernate.orm.jdbc.bind: WARN

app:
  mail:
    enabled: false
